export const API_BASE = '/api';
export const CLERK_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY || '';
export const DEEPSEEK_KEY = import.meta.env.VITE_DEEPSEEK_KEY || '';
export const DEEPSEEK_URL = 'https://api.deepseek.com/chat/completions';
export const STORAGE_KEYS = {
    EQUIPMENT: 'grind_equipment',
    SETUP_DONE: 'grind_setup_done',
    WORKOUT_STATE: 'grind_workout_state',
    USER_DATA: 'grind_user_data',
    WORKOUT_HISTORY: 'grind_workout_history'
};
export const CATEGORIES = ['All', 'Full Body', 'Upper Body', 'Lower Body', 'Core', 'Cardio', 'Recovery'];
export const CIRCUMFERENCE = 2 * Math.PI * 54;

export const EQUIPMENT = [
    { id: 'Bodyweight', icon: '🤸', name: 'Bodyweight', desc: 'Push-ups, squats, planks — no gear needed', alwaysOn: true },
    { id: 'Long Band', icon: '🟡', name: 'Long Resistance Band', desc: 'Full-length loop bands for pressing, rowing, curls' },
    { id: 'Short Band', icon: '🔴', name: 'Short / Mini Band', desc: 'Hip-circle style bands for glutes & legs' },
    { id: 'Pull-up Bar', icon: '🔩', name: 'Doorway Pull-Up Bar', desc: 'Mounted bar for pull-ups, chin-ups, hangs' },
    { id: 'Jump Rope', icon: '🪢', name: 'Jump Rope', desc: 'Speed rope or weighted rope for cardio & conditioning' },
];

export const WORKOUTS = [
    {
        id: 'fb-30',
        title: 'Full Body Blitz',
        category: 'Full Body',
        duration: 30,
        intensity: 'high',
        equipment: ['Bodyweight', 'Pull-up Bar', 'Long Band'],
        muscles: 'Chest · Back · Legs · Core · Shoulders',
        desc: 'Hit every muscle group with a mix of pull-ups, push-ups, squats, and band work.',
        steps: [
            { phase: 'Warm-Up', name: 'Jumping Jacks', duration: 45, type: 'exercise', tips: '45 seconds' },
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 30, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 30, type: 'exercise', tips: '15 reps' },
            { phase: 'Block 1 — Push', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Block 1 — Push', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 1 — Push', name: 'Band Chest Press', duration: 40, type: 'exercise', set: 2, reps: 12 },
            { phase: 'Block 1 — Push', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 1 — Push', name: 'Diamond Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
            { phase: 'Block 1 — Push', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Block 2 — Pull', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Block 2 — Pull', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Block 2 — Pull', name: 'Band Rows', duration: 40, type: 'exercise', set: 2, reps: 12 },
            { phase: 'Block 2 — Pull', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 2 — Pull', name: 'Chin-Ups', duration: 45, type: 'exercise', set: 3, reps: 6 },
            { phase: 'Block 2 — Pull', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Block 3 — Legs', name: 'Band Squats', duration: 45, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Block 3 — Legs', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 3 — Legs', name: 'Lunges', duration: 45, type: 'exercise', set: 2, reps: '12 each' },
            { phase: 'Block 3 — Legs', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 3 — Legs', name: 'Band Romanian Deadlifts', duration: 40, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Block 3 — Legs', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Finisher', name: 'Plank Hold', duration: 45, type: 'exercise', tips: '45 seconds' },
            { phase: 'Finisher', name: 'Rest', duration: 15, type: 'rest' },
            { phase: 'Finisher', name: 'Mountain Climbers', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '15s each leg' },
            { phase: 'Cool-Down', name: 'Chest Doorway Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Deep Breathing', duration: 30, type: 'exercise', tips: '30 seconds' },
        ]
    },
    {
        id: 'fb-20-bw',
        title: 'Bodyweight Express',
        category: 'Full Body',
        duration: 20,
        intensity: 'medium',
        equipment: ['Bodyweight'],
        muscles: 'Full Body · No Equipment Needed',
        desc: 'Quick and effective full body session with zero equipment. Perfect for travel or minimal space.',
        steps: [
            { phase: 'Warm-Up', name: 'High Knees', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 20, type: 'exercise', tips: '20 seconds' },
            { phase: 'Warm-Up', name: 'Hip Circles', duration: 20, type: 'exercise', tips: '10 each direction' },
            { phase: 'Circuit — Round 1', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Circuit — Round 1', name: 'Bodyweight Squats', duration: 40, type: 'exercise', set: 1, reps: 20 },
            { phase: 'Circuit — Round 1', name: 'Plank Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Circuit — Round 1', name: 'Glute Bridges', duration: 35, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Circuit — Round 1', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Circuit — Round 2', name: 'Wide Push-Ups', duration: 40, type: 'exercise', set: 2, reps: 12 },
            { phase: 'Circuit — Round 2', name: 'Jump Squats', duration: 35, type: 'exercise', set: 2, reps: 12 },
            { phase: 'Circuit — Round 2', name: 'Dead Bugs', duration: 35, type: 'exercise', tips: '10 each side' },
            { phase: 'Circuit — Round 2', name: 'Superman Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Circuit — Round 2', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Circuit — Round 3', name: 'Decline Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
            { phase: 'Circuit — Round 3', name: 'Bulgarian Split Squats', duration: 50, type: 'exercise', set: 3, reps: '8 each' },
            { phase: 'Circuit — Round 3', name: 'Bicycle Crunches', duration: 35, type: 'exercise', tips: '20 reps' },
            { phase: 'Circuit — Round 3', name: 'Calf Raises', duration: 30, type: 'exercise', set: 3, reps: 20 },
            { phase: 'Cool-Down', name: 'Child\'s Pose', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Standing Hamstring Stretch', duration: 30, type: 'exercise', tips: '15s each' },
        ]
    },
    {
        id: 'upper-push',
        title: 'Push Day',
        category: 'Upper Body',
        duration: 25,
        intensity: 'high',
        equipment: ['Bodyweight', 'Long Band'],
        muscles: 'Chest · Shoulders · Triceps',
        desc: 'Chest, shoulders, and triceps with push-ups variations and band presses.',
        steps: [
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 25, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Scapular Push-Ups', duration: 25, type: 'exercise', tips: '10 reps' },
            { phase: 'Chest', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Chest', name: 'Band Chest Press', duration: 40, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Chest', name: 'Wide Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Shoulders', name: 'Band Overhead Press', duration: 40, type: 'exercise', set: 1, reps: 12 },
            { phase: 'Shoulders', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Shoulders', name: 'Band Lateral Raises', duration: 35, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Shoulders', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Shoulders', name: 'Pike Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
            { phase: 'Shoulders', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Triceps', name: 'Diamond Push-Ups', duration: 35, type: 'exercise', set: 1, reps: 12 },
            { phase: 'Triceps', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Triceps', name: 'Band Tricep Pushdowns', duration: 35, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Triceps', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Triceps', name: 'Bench Dips', duration: 35, type: 'exercise', set: 3, reps: 15 },
            { phase: 'Cool-Down', name: 'Chest Doorway Stretch', duration: 30, type: 'exercise', tips: '15s each side' },
            { phase: 'Cool-Down', name: 'Tricep Stretch', duration: 30, type: 'exercise', tips: '15s each arm' },
        ]
    },
    {
        id: 'upper-pull',
        title: 'Pull Day',
        category: 'Upper Body',
        duration: 28,
        intensity: 'high',
        equipment: ['Pull-up Bar', 'Long Band'],
        muscles: 'Back · Biceps · Rear Delts',
        desc: 'Back and bicep focused with pull-up variations and heavy band rows.',
        steps: [
            { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 25, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Cat-Cow Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Scapular Pull-Ups', duration: 25, type: 'exercise', tips: '8 reps' },
            { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
            { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 2, reps: 8 },
            { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
            { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 3, reps: 6 },
            { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
            { phase: 'Rows', name: 'Band Bent-Over Rows', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Rows', name: 'Band Single-Arm Rows', duration: 45, type: 'exercise', set: 2, reps: '12 each' },
            { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Rows', name: 'Band Face Pulls', duration: 35, type: 'exercise', set: 3, reps: 15 },
            { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Biceps', name: 'Chin-Ups', duration: 40, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Biceps', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Biceps', name: 'Band Curls', duration: 35, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Biceps', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Biceps', name: 'Band Hammer Curls', duration: 35, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Cool-Down', name: 'Lat Stretch', duration: 30, type: 'exercise', tips: '15s each side' },
            { phase: 'Cool-Down', name: 'Bicep Wall Stretch', duration: 30, type: 'exercise', tips: '15s each arm' },
            { phase: 'Cool-Down', name: 'Deep Breathing', duration: 30, type: 'exercise', tips: '30 seconds' },
        ]
    },
    {
        id: 'lower-bands',
        title: 'Legs & Glutes',
        category: 'Lower Body',
        duration: 28,
        intensity: 'high',
        equipment: ['Short Band', 'Long Band'],
        muscles: 'Quads · Glutes · Hamstrings · Calves',
        desc: 'Brutal lower body session using both long and short bands for maximum resistance.',
        steps: [
            { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 30, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Leg Swings', duration: 30, type: 'exercise', tips: '10 each leg' },
            { phase: 'Warm-Up', name: 'Banded Lateral Walks', duration: 30, type: 'exercise', tips: '10 each direction' },
            { phase: 'Quads & Glutes', name: 'Banded Squats (long band)', duration: 45, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Quads & Glutes', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Quads & Glutes', name: 'Banded Squats (long band)', duration: 45, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Quads & Glutes', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Quads & Glutes', name: 'Banded Squats (long band)', duration: 45, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Quads & Glutes', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Unilateral', name: 'Bulgarian Split Squats', duration: 50, type: 'exercise', set: 1, reps: '10 each' },
            { phase: 'Unilateral', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Unilateral', name: 'Banded Reverse Lunges', duration: 50, type: 'exercise', set: 2, reps: '10 each' },
            { phase: 'Unilateral', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Glute Focus', name: 'Banded Glute Bridges', duration: 40, type: 'exercise', set: 1, reps: 20 },
            { phase: 'Glute Focus', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Glute Focus', name: 'Banded Kickbacks', duration: 45, type: 'exercise', set: 2, reps: '12 each' },
            { phase: 'Glute Focus', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Glute Focus', name: 'Banded Clamshells', duration: 40, type: 'exercise', set: 3, reps: '15 each' },
            { phase: 'Glute Focus', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Hamstrings', name: 'Band Romanian Deadlifts', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Hamstrings', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Hamstrings', name: 'Single-Leg RDL', duration: 50, type: 'exercise', set: 2, reps: '10 each' },
            { phase: 'Hamstrings', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Finisher', name: 'Wall Sit', duration: 45, type: 'exercise', tips: '45 seconds' },
            { phase: 'Finisher', name: 'Calf Raises', duration: 35, type: 'exercise', set: 1, reps: 25 },
            { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Cool-Down', name: 'Pigeon Stretch', duration: 40, type: 'exercise', tips: '20s each side' },
        ]
    },
    {
        id: 'core-killer',
        title: 'Core Destroyer',
        category: 'Core',
        duration: 18,
        intensity: 'high',
        equipment: ['Bodyweight', 'Short Band'],
        muscles: 'Abs · Obliques · Lower Back · Hip Flexors',
        desc: 'Intense core session with anti-rotation, flexion, and stability work.',
        steps: [
            { phase: 'Warm-Up', name: 'Cat-Cow Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Dead Bugs', duration: 30, type: 'exercise', tips: '8 each side' },
            { phase: 'Block 1', name: 'Plank Hold', duration: 45, type: 'exercise', set: 1, tips: '45 seconds' },
            { phase: 'Block 1', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 1', name: 'Bicycle Crunches', duration: 35, type: 'exercise', set: 1, reps: 20 },
            { phase: 'Block 1', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 1', name: 'Mountain Climbers', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Block 1', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 2', name: 'Side Plank (L)', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Block 2', name: 'Side Plank (R)', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Block 2', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 2', name: 'Leg Raises', duration: 35, type: 'exercise', set: 1, reps: 12 },
            { phase: 'Block 2', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 2', name: 'Flutter Kicks', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Block 2', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 3', name: 'Banded Pallof Press', duration: 35, type: 'exercise', set: 1, reps: '10 each' },
            { phase: 'Block 3', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 3', name: 'V-Ups', duration: 30, type: 'exercise', set: 1, reps: 12 },
            { phase: 'Block 3', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Block 3', name: 'Hollow Body Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Child\'s Pose', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Cobra Stretch', duration: 25, type: 'exercise', tips: '25 seconds' },
        ]
    },
    {
        id: 'hiit-20',
        title: 'HIIT Burnout',
        category: 'Cardio',
        duration: 20,
        intensity: 'high',
        equipment: ['Bodyweight', 'Short Band'],
        muscles: 'Full Body · Cardio · Fat Burn',
        desc: 'High intensity intervals — 30s work / 15s rest. Pure cardio burn with bodyweight moves.',
        steps: [
            { phase: 'Warm-Up', name: 'Jumping Jacks', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'High Knees', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 20, type: 'exercise', tips: '20 seconds' },
            ...['Burpees', 'Jump Squats', 'Mountain Climbers', 'Push-Ups', 'High Knees',
                'Banded Squat Jumps', 'Plank Jacks', 'Tuck Jumps', 'Speed Skaters', 'Burpees'
            ].flatMap((name, i) => [
                { phase: `Round ${Math.floor(i/2)+1}`, name, duration: 30, type: 'exercise', tips: 'All out!' },
                { phase: `Round ${Math.floor(i/2)+1}`, name: 'Rest', duration: 15, type: 'rest' },
            ]),
            { phase: 'Finisher', name: 'Burpee Hold', duration: 30, type: 'exercise', tips: 'Max effort!' },
            { phase: 'Cool-Down', name: 'Walk in Place', duration: 30, type: 'exercise', tips: 'Slow it down' },
            { phase: 'Cool-Down', name: 'Standing Hamstring Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Cool-Down', name: 'Deep Breathing', duration: 40, type: 'exercise', tips: '40 seconds' },
        ]
    },
    {
        id: 'bands-upper',
        title: 'Band Upper Sculpt',
        category: 'Upper Body',
        duration: 25,
        intensity: 'medium',
        equipment: ['Long Band'],
        muscles: 'Shoulders · Chest · Back · Arms',
        desc: 'Full upper body session using only a long resistance band. Great for travel.',
        steps: [
            { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 25, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Band Dislocates', duration: 25, type: 'exercise', tips: '10 reps' },
            { phase: 'Warm-Up', name: 'Band Pass-Throughs', duration: 25, type: 'exercise', tips: '10 reps' },
            { phase: 'Shoulders', name: 'Band Overhead Press', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Shoulders', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Shoulders', name: 'Band Lateral Raises', duration: 35, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Shoulders', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Shoulders', name: 'Band Front Raises', duration: 35, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Shoulders', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Chest & Back', name: 'Band Chest Press', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Chest & Back', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Chest & Back', name: 'Band Bent-Over Rows', duration: 40, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Chest & Back', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Chest & Back', name: 'Band Chest Flyes', duration: 35, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Chest & Back', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Chest & Back', name: 'Band Face Pulls', duration: 35, type: 'exercise', set: 4, reps: 15 },
            { phase: 'Chest & Back', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Arms', name: 'Band Curls', duration: 35, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Arms', name: 'Rest', duration: 25, type: 'rest' },
            { phase: 'Arms', name: 'Band Tricep Pushdowns', duration: 35, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Arms', name: 'Rest', duration: 25, type: 'rest' },
            { phase: 'Arms', name: 'Band Hammer Curls', duration: 30, type: 'exercise', set: 3, reps: 12 },
            { phase: 'Arms', name: 'Rest', duration: 25, type: 'rest' },
            { phase: 'Arms', name: 'Band Overhead Tricep Ext.', duration: 30, type: 'exercise', set: 4, reps: 12 },
            { phase: 'Cool-Down', name: 'Band Stretch Overhead', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Cross-Body Shoulder Stretch', duration: 30, type: 'exercise', tips: '15s each' },
        ]
    },
    {
        id: 'bands-lower',
        title: 'Band Leg Burner',
        category: 'Lower Body',
        duration: 22,
        intensity: 'medium',
        equipment: ['Long Band', 'Short Band'],
        muscles: 'Glutes · Quads · Hamstrings · Abductors',
        desc: 'Resistance band leg day combining long band squats with short band glute activation.',
        steps: [
            { phase: 'Warm-Up', name: 'Banded Lateral Walks', duration: 30, type: 'exercise', tips: '10 each way' },
            { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 25, type: 'exercise', tips: '12 reps' },
            { phase: 'Warm-Up', name: 'Banded Monster Walks', duration: 30, type: 'exercise', tips: '10 each way' },
            { phase: 'Squats', name: 'Banded Front Squats', duration: 45, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Squats', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Squats', name: 'Banded Sumo Squats', duration: 45, type: 'exercise', set: 2, reps: 15 },
            { phase: 'Squats', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Squats', name: 'Banded Pulse Squats', duration: 30, type: 'exercise', tips: '20 pulses' },
            { phase: 'Squats', name: 'Rest', duration: 45, type: 'rest' },
            { phase: 'Glutes', name: 'Banded Glute Bridges', duration: 40, type: 'exercise', set: 1, reps: 20 },
            { phase: 'Glutes', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Glutes', name: 'Banded Fire Hydrants', duration: 40, type: 'exercise', set: 2, reps: '12 each' },
            { phase: 'Glutes', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Glutes', name: 'Banded Donkey Kicks', duration: 40, type: 'exercise', set: 3, reps: '12 each' },
            { phase: 'Glutes', name: 'Rest', duration: 35, type: 'rest' },
            { phase: 'Hamstrings', name: 'Band Good Mornings', duration: 40, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Hamstrings', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Hamstrings', name: 'Banded Romanian Deadlifts', duration: 40, type: 'exercise', set: 2, reps: 12 },
            { phase: 'Cool-Down', name: 'Pigeon Stretch', duration: 40, type: 'exercise', tips: '20s each side' },
            { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '15s each' },
        ]
    },
    {
        id: 'bar-master',
        title: 'Bar Mastery',
        category: 'Upper Body',
        duration: 25,
        intensity: 'high',
        equipment: ['Pull-up Bar'],
        muscles: 'Back · Biceps · Core · Grip',
        desc: 'Complete pull-up bar session with grip variations, hanging core work, and dead hangs.',
        steps: [
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 25, type: 'exercise', tips: '25 seconds' },
            { phase: 'Warm-Up', name: 'Scapular Pull-Ups', duration: 30, type: 'exercise', tips: '10 reps' },
            { phase: 'Warm-Up', name: 'Dead Hang', duration: 20, type: 'exercise', tips: '20 seconds' },
            { phase: 'Pull-Ups', name: 'Pull-Ups (overhand)', duration: 45, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Pull-Ups', name: 'Rest', duration: 75, type: 'rest' },
            { phase: 'Pull-Ups', name: 'Pull-Ups (overhand)', duration: 45, type: 'exercise', set: 2, reps: 8 },
            { phase: 'Pull-Ups', name: 'Rest', duration: 75, type: 'rest' },
            { phase: 'Pull-Ups', name: 'Pull-Ups (overhand)', duration: 45, type: 'exercise', set: 3, reps: 6 },
            { phase: 'Pull-Ups', name: 'Rest', duration: 75, type: 'rest' },
            { phase: 'Chin-Ups', name: 'Chin-Ups (underhand)', duration: 40, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Chin-Ups', name: 'Rest', duration: 60, type: 'rest' },
            { phase: 'Chin-Ups', name: 'Chin-Ups (underhand)', duration: 40, type: 'exercise', set: 2, reps: 6 },
            { phase: 'Chin-Ups', name: 'Rest', duration: 60, type: 'rest' },
            { phase: 'Grip & Core', name: 'Hanging Knee Raises', duration: 35, type: 'exercise', set: 1, reps: 10 },
            { phase: 'Grip & Core', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Grip & Core', name: 'Hanging Knee Raises', duration: 35, type: 'exercise', set: 2, reps: 10 },
            { phase: 'Grip & Core', name: 'Rest', duration: 40, type: 'rest' },
            { phase: 'Grip & Core', name: 'Dead Hang Hold', duration: 40, type: 'exercise', tips: '40 seconds' },
            { phase: 'Grip & Core', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Grip & Core', name: 'Dead Hang Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Cool-Down', name: 'Lat Stretch', duration: 30, type: 'exercise', tips: '15s each side' },
            { phase: 'Cool-Down', name: 'Bicep Wall Stretch', duration: 25, type: 'exercise', tips: '12s each arm' },
            { phase: 'Cool-Down', name: 'Deep Breathing', duration: 30, type: 'exercise', tips: '30 seconds' },
        ]
    },
    {
        id: 'mobility-flow',
        title: 'Mobility Flow',
        category: 'Recovery',
        duration: 15,
        intensity: 'low',
        equipment: ['Long Band'],
        muscles: 'Full Body · Flexibility · Joint Health',
        desc: 'Active recovery and mobility work. Great for rest days or post-workout cool-down.',
        steps: [
            { phase: 'Breathing', name: 'Diaphragmatic Breathing', duration: 45, type: 'exercise', tips: '45 seconds' },
            { phase: 'Upper Body', name: 'Neck Circles', duration: 30, type: 'exercise', tips: '15s each way' },
            { phase: 'Upper Body', name: 'Band Shoulder Dislocates', duration: 35, type: 'exercise', tips: '10 slow reps' },
            { phase: 'Upper Body', name: 'Thread the Needle', duration: 40, type: 'exercise', tips: '20s each side' },
            { phase: 'Upper Body', name: 'Chest Doorway Stretch', duration: 40, type: 'exercise', tips: '20s each side' },
            { phase: 'Upper Body', name: 'Cat-Cow Stretch', duration: 40, type: 'exercise', tips: '10 slow reps' },
            { phase: 'Spine', name: 'Thoracic Rotations', duration: 40, type: 'exercise', tips: '8 each side' },
            { phase: 'Spine', name: 'Scorpion Stretch', duration: 40, type: 'exercise', tips: '20s each side' },
            { phase: 'Spine', name: 'Cobra to Child\'s Pose', duration: 45, type: 'exercise', tips: '8 slow reps' },
            { phase: 'Lower Body', name: 'Hip Circles', duration: 30, type: 'exercise', tips: '10 each direction' },
            { phase: 'Lower Body', name: '90/90 Hip Stretch', duration: 50, type: 'exercise', tips: '25s each side' },
            { phase: 'Lower Body', name: 'Pigeon Pose', duration: 50, type: 'exercise', tips: '25s each side' },
            { phase: 'Lower Body', name: 'Deep Squat Hold', duration: 40, type: 'exercise', tips: '40 seconds' },
            { phase: 'Lower Body', name: 'Calf Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Close', name: 'Standing Forward Fold', duration: 35, type: 'exercise', tips: '35 seconds' },
            { phase: 'Close', name: 'Deep Breathing', duration: 40, type: 'exercise', tips: '40 seconds' },
        ]
    },
    {
        id: 'jr-basics',
        title: 'Rope Burner',
        category: 'Cardio',
        duration: 18,
        intensity: 'high',
        equipment: ['Jump Rope'],
        muscles: 'Calves · Shoulders · Cardio · Full Body',
        desc: 'Classic jump rope intervals — 30s on, 10s rest. Four-set blocks with varied footwork.',
        steps: [
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 20, type: 'exercise', tips: '20 seconds' },
            { phase: 'Warm-Up', name: 'Calf Raises', duration: 25, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Light Jump Rope', duration: 30, type: 'exercise', tips: 'Easy pace' },
            { phase: 'Block 1 — Basic Bounce', name: 'Jump Rope', duration: 30, type: 'exercise', set: 1, reps: '30s' },
            { phase: 'Block 1 — Basic Bounce', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 1 — Basic Bounce', name: 'Jump Rope', duration: 30, type: 'exercise', set: 2, reps: '30s' },
            { phase: 'Block 1 — Basic Bounce', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 1 — Basic Bounce', name: 'Jump Rope', duration: 30, type: 'exercise', set: 3, reps: '30s' },
            { phase: 'Block 1 — Basic Bounce', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 1 — Basic Bounce', name: 'Jump Rope', duration: 30, type: 'exercise', set: 4, reps: '30s' },
            { phase: 'Block 1 — Basic Bounce', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Block 2 — High Knees', name: 'High Knee Jump Rope', duration: 30, type: 'exercise', set: 1, reps: '30s' },
            { phase: 'Block 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 2 — High Knees', name: 'High Knee Jump Rope', duration: 30, type: 'exercise', set: 2, reps: '30s' },
            { phase: 'Block 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 2 — High Knees', name: 'High Knee Jump Rope', duration: 30, type: 'exercise', set: 3, reps: '30s' },
            { phase: 'Block 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Block 2 — High Knees', name: 'High Knee Jump Rope', duration: 30, type: 'exercise', set: 4, reps: '30s' },
            { phase: 'Block 2 — High Knees', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Cool-Down', name: 'Walk in Place', duration: 30, type: 'exercise', tips: 'Slow it down' },
            { phase: 'Cool-Down', name: 'Calf Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '15s each' },
        ]
    },
    {
        id: 'jr-mixed',
        title: 'Rope & Bodyweight Blast',
        category: 'Cardio',
        duration: 22,
        intensity: 'high',
        equipment: ['Jump Rope', 'Bodyweight'],
        muscles: 'Full Body · Cardio · Conditioning',
        desc: 'Alternates jump rope intervals with bodyweight strength moves for a full cardio + muscle session.',
        steps: [
            { phase: 'Warm-Up', name: 'Light Jump Rope', duration: 30, type: 'exercise', tips: 'Easy pace' },
            { phase: 'Warm-Up', name: 'Arm Circles', duration: 20, type: 'exercise', tips: '20 seconds' },
            { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 25, type: 'exercise', tips: '12 reps' },
            { phase: 'Round 1', name: 'Jump Rope', duration: 30, type: 'exercise', set: 1, reps: '30s' },
            { phase: 'Round 1', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 1', name: 'Push-Ups', duration: 35, type: 'exercise', set: 1, reps: 15 },
            { phase: 'Round 1', name: 'Rest', duration: 15, type: 'rest' },
            { phase: 'Round 1', name: 'Jump Rope', duration: 30, type: 'exercise', set: 2, reps: '30s' },
            { phase: 'Round 1', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 1', name: 'Bodyweight Squats', duration: 35, type: 'exercise', set: 2, reps: 20 },
            { phase: 'Round 1', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Round 2', name: 'High Knee Jump Rope', duration: 30, type: 'exercise', set: 1, reps: '30s' },
            { phase: 'Round 2', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 2', name: 'Diamond Push-Ups', duration: 35, type: 'exercise', set: 1, reps: 10 },
            { phase: 'Round 2', name: 'Rest', duration: 15, type: 'rest' },
            { phase: 'Round 2', name: 'Jump Rope', duration: 30, type: 'exercise', set: 2, reps: '30s' },
            { phase: 'Round 2', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 2', name: 'Lunges', duration: 40, type: 'exercise', set: 2, reps: '10 each' },
            { phase: 'Round 2', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Round 3', name: 'Alternating Step Rope', duration: 30, type: 'exercise', set: 1, reps: '30s' },
            { phase: 'Round 3', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 3', name: 'Burpees', duration: 35, type: 'exercise', set: 1, reps: 8 },
            { phase: 'Round 3', name: 'Rest', duration: 15, type: 'rest' },
            { phase: 'Round 3', name: 'Jump Rope', duration: 30, type: 'exercise', set: 2, reps: '30s' },
            { phase: 'Round 3', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Round 3', name: 'Mountain Climbers', duration: 30, type: 'exercise', tips: '30 seconds' },
            { phase: 'Round 3', name: 'Rest', duration: 20, type: 'rest' },
            { phase: 'Finisher', name: 'Max Effort Jump Rope', duration: 30, type: 'exercise', tips: 'All out!' },
            { phase: 'Finisher', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Finisher', name: 'Max Effort Jump Rope', duration: 30, type: 'exercise', tips: 'Last push!' },
            { phase: 'Cool-Down', name: 'Walk in Place', duration: 30, type: 'exercise', tips: 'Slow it down' },
            { phase: 'Cool-Down', name: 'Calf Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Cool-Down', name: 'Standing Hamstring Stretch', duration: 30, type: 'exercise', tips: '15s each' },
        ]
    },
    {
        id: 'jr-tabata',
        title: 'Rope Tabata',
        category: 'Cardio',
        duration: 15,
        intensity: 'high',
        equipment: ['Jump Rope'],
        muscles: 'Cardio · Calves · Shoulders · Fat Burn',
        desc: 'Tabata-style 20s on / 10s rest jump rope intervals. Short, brutal, effective.',
        steps: [
            { phase: 'Warm-Up', name: 'Light Jump Rope', duration: 30, type: 'exercise', tips: 'Easy pace' },
            { phase: 'Warm-Up', name: 'Calf Raises', duration: 20, type: 'exercise', tips: '15 reps' },
            { phase: 'Warm-Up', name: 'Wrist Circles', duration: 15, type: 'exercise', tips: '15 seconds' },
            { phase: 'Tabata 1 — Basic', name: 'Jump Rope Sprint', duration: 20, type: 'exercise', set: 1, reps: '20s' },
            { phase: 'Tabata 1 — Basic', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 1 — Basic', name: 'Jump Rope Sprint', duration: 20, type: 'exercise', set: 2, reps: '20s' },
            { phase: 'Tabata 1 — Basic', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 1 — Basic', name: 'Jump Rope Sprint', duration: 20, type: 'exercise', set: 3, reps: '20s' },
            { phase: 'Tabata 1 — Basic', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 1 — Basic', name: 'Jump Rope Sprint', duration: 20, type: 'exercise', set: 4, reps: '20s' },
            { phase: 'Tabata 1 — Basic', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Tabata 2 — High Knees', name: 'High Knee Rope', duration: 20, type: 'exercise', set: 1, reps: '20s' },
            { phase: 'Tabata 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 2 — High Knees', name: 'High Knee Rope', duration: 20, type: 'exercise', set: 2, reps: '20s' },
            { phase: 'Tabata 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 2 — High Knees', name: 'High Knee Rope', duration: 20, type: 'exercise', set: 3, reps: '20s' },
            { phase: 'Tabata 2 — High Knees', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 2 — High Knees', name: 'High Knee Rope', duration: 20, type: 'exercise', set: 4, reps: '20s' },
            { phase: 'Tabata 2 — High Knees', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Criss Cross Rope', duration: 20, type: 'exercise', set: 1, reps: '20s' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Criss Cross Rope', duration: 20, type: 'exercise', set: 2, reps: '20s' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Criss Cross Rope', duration: 20, type: 'exercise', set: 3, reps: '20s' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Rest', duration: 10, type: 'rest' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Criss Cross Rope', duration: 20, type: 'exercise', set: 4, reps: '20s' },
            { phase: 'Tabata 3 — Criss Cross', name: 'Rest', duration: 30, type: 'rest' },
            { phase: 'Cool-Down', name: 'Walk in Place', duration: 30, type: 'exercise', tips: 'Breathe deep' },
            { phase: 'Cool-Down', name: 'Calf Stretch', duration: 30, type: 'exercise', tips: '15s each' },
            { phase: 'Cool-Down', name: 'Deep Breathing', duration: 30, type: 'exercise', tips: '30 seconds' },
        ]
    },
];
