export const WORKOUTS = [
  {
    id: 'fb-30',
    title: 'Full Body Blitz',
    category: 'Full Body',
    duration: 30,
    intensity: 'high',
    equipment: ['Bodyweight', 'Pull-up Bar', 'Long Band'],
    muscles: 'Chest · Back · Legs · Core · Shoulders',
    desc: 'Hit every muscle group with a mix of pull-ups, push-ups, squats, and band work.',
    steps: [
      { phase: 'Warm-Up', name: 'Jumping Jacks', duration: 45, type: 'exercise', tips: '45 seconds' },
      { phase: 'Warm-Up', name: 'Arm Circles', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 30, type: 'exercise', tips: '15 reps' },
      { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 30, type: 'exercise', tips: '15 reps' },
      { phase: 'Block 1 — Push', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Block 1 — Push', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Block 1 — Push', name: 'Band Chest Press', duration: 40, type: 'exercise', set: 2, reps: 12 },
      { phase: 'Block 1 — Push', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Block 1 — Push', name: 'Diamond Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
      { phase: 'Block 1 — Push', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Block 2 — Pull', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 1, reps: 8 },
      { phase: 'Block 2 — Pull', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Block 2 — Pull', name: 'Band Rows', duration: 40, type: 'exercise', set: 2, reps: 12 },
      { phase: 'Block 2 — Pull', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Block 2 — Pull', name: 'Chin-Ups', duration: 45, type: 'exercise', set: 3, reps: 6 },
      { phase: 'Block 2 — Pull', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Block 3 — Legs', name: 'Band Squats', duration: 45, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Block 3 — Legs', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Block 3 — Legs', name: 'Lunges', duration: 45, type: 'exercise', set: 2, reps: '12 each' },
      { phase: 'Block 3 — Legs', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Block 3 — Legs', name: 'Band Romanian Deadlifts', duration: 40, type: 'exercise', set: 3, reps: 12 },
      { phase: 'Block 3 — Legs', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Finisher', name: 'Plank Hold', duration: 45, type: 'exercise', tips: '45 seconds' },
      { phase: 'Finisher', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Finisher', name: 'Mountain Climbers', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '15s each leg' },
      { phase: 'Cool-Down', name: 'Chest Doorway Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Cool-Down', name: 'Deep Breathing', duration: 30, type: 'exercise', tips: '30 seconds' },
    ]
  },
  {
    id: 'fb-20-bw',
    title: 'Bodyweight Express',
    category: 'Full Body',
    duration: 20,
    intensity: 'medium',
    equipment: ['Bodyweight'],
    muscles: 'Full Body · No Equipment Needed',
    desc: 'Quick and effective full body session with zero equipment. Perfect for travel or minimal space.',
    steps: [
      { phase: 'Warm-Up', name: 'High Knees', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Arm Circles', duration: 20, type: 'exercise', tips: '20 seconds' },
      { phase: 'Warm-Up', name: 'Hip Circles', duration: 20, type: 'exercise', tips: '10 each direction' },
      { phase: 'Circuit — Round 1', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Circuit — Round 1', name: 'Bodyweight Squats', duration: 40, type: 'exercise', set: 1, reps: 20 },
      { phase: 'Circuit — Round 1', name: 'Plank Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Circuit — Round 1', name: 'Glute Bridges', duration: 35, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Circuit — Round 1', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Circuit — Round 2', name: 'Wide Push-Ups', duration: 40, type: 'exercise', set: 2, reps: 12 },
      { phase: 'Circuit — Round 2', name: 'Jump Squats', duration: 35, type: 'exercise', set: 2, reps: 12 },
      { phase: 'Circuit — Round 2', name: 'Dead Bugs', duration: 35, type: 'exercise', tips: '10 each side' },
      { phase: 'Circuit — Round 2', name: 'Superman Hold', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Circuit — Round 2', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Circuit — Round 3', name: 'Decline Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
      { phase: 'Circuit — Round 3', name: 'Bulgarian Split Squats', duration: 50, type: 'exercise', set: 3, reps: '8 each' },
      { phase: 'Circuit — Round 3', name: 'Bicycle Crunches', duration: 35, type: 'exercise', tips: '20 reps' },
      { phase: 'Circuit — Round 3', name: 'Calf Raises', duration: 30, type: 'exercise', set: 3, reps: 20 },
      { phase: 'Cool-Down', name: 'Child\'s Pose', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Cool-Down', name: 'Standing Hamstring Stretch', duration: 30, type: 'exercise', tips: '15s each' },
    ]
  },
  {
    id: 'upper-push',
    title: 'Push Day',
    category: 'Upper Body',
    duration: 25,
    intensity: 'high',
    equipment: ['Bodyweight', 'Long Band'],
    muscles: 'Chest · Shoulders · Triceps',
    desc: 'Chest, shoulders, and triceps with push-ups variations and band presses.',
    steps: [
      { phase: 'Warm-Up', name: 'Arm Circles', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 25, type: 'exercise', tips: '15 reps' },
      { phase: 'Warm-Up', name: 'Scapular Push-Ups', duration: 25, type: 'exercise', tips: '10 reps' },
      { phase: 'Chest', name: 'Push-Ups', duration: 40, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Chest', name: 'Band Chest Press', duration: 40, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Chest', name: 'Wide Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 12 },
      { phase: 'Chest', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Shoulders', name: 'Band Overhead Press', duration: 40, type: 'exercise', set: 1, reps: 12 },
      { phase: 'Shoulders', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Shoulders', name: 'Band Lateral Raises', duration: 35, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Shoulders', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Shoulders', name: 'Pike Push-Ups', duration: 40, type: 'exercise', set: 3, reps: 10 },
      { phase: 'Shoulders', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Triceps', name: 'Diamond Push-Ups', duration: 35, type: 'exercise', set: 1, reps: 12 },
      { phase: 'Triceps', name: 'Rest', duration: 35, type: 'rest' },
      { phase: 'Triceps', name: 'Band Tricep Pushdowns', duration: 35, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Triceps', name: 'Rest', duration: 35, type: 'rest' },
      { phase: 'Triceps', name: 'Bench Dips', duration: 35, type: 'exercise', set: 3, reps: 15 },
      { phase: 'Cool-Down', name: 'Chest Doorway Stretch', duration: 30, type: 'exercise', tips: '15s each side' },
      { phase: 'Cool-Down', name: 'Tricep Stretch', duration: 30, type: 'exercise', tips: '15s each arm' },
    ]
  },
  {
    id: 'upper-pull',
    title: 'Pull Day',
    category: 'Upper Body',
    duration: 28,
    intensity: 'high',
    equipment: ['Pull-up Bar', 'Long Band'],
    muscles: 'Back · Biceps · Rear Delts',
    desc: 'Back and bicep focused with pull-up variations and heavy band rows.',
    steps: [
      { phase: 'Warm-Up', name: 'Band Pull-Aparts', duration: 25, type: 'exercise', tips: '15 reps' },
      { phase: 'Warm-Up', name: 'Cat-Cow Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Scapular Pull-Ups', duration: 25, type: 'exercise', tips: '8 reps' },
      { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 1, reps: 8 },
      { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
      { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 2, reps: 8 },
      { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
      { phase: 'Back', name: 'Pull-Ups', duration: 45, type: 'exercise', set: 3, reps: 6 },
      { phase: 'Back', name: 'Rest', duration: 60, type: 'rest' },
      { phase: 'Rows', name: 'Band Bent-Over Rows', duration: 40, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Rows', name: 'Band Single-Arm Rows', duration: 45, type: 'exercise', set: 2, reps: '12 each' },
      { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Rows', name: 'Band Face Pulls', duration: 35, type: 'exercise', set: 3, reps: 15 },
      { phase: 'Rows', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Biceps', name: 'Chin-Ups', duration: 40, type: 'exercise', set: 1, reps: 8 },
      { phase: 'Biceps', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Biceps', name: 'Band Curls', duration: 35, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Biceps', name: 'Rest', duration: 35, type: 'rest' },
      { phase: 'Biceps', name: 'Band Hammer Curls', duration: 35, type: 'exercise', set: 3, reps: 12 },
      { phase: 'Cool-Down', name: 'Lat Stretch', duration: 30, type: 'exercise', tips: '15s each side' },
    ]
  },
  {
    id: 'lower-legs',
    title: 'Leg Day',
    category: 'Lower Body',
    duration: 30,
    intensity: 'high',
    equipment: ['Bodyweight', 'Long Band'],
    muscles: 'Quads · Hamstrings · Glutes · Calves',
    desc: 'Complete lower body workout with squats, lunges, and band leg exercises.',
    steps: [
      { phase: 'Warm-Up', name: 'High Knees', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Hip Circles', duration: 20, type: 'exercise', tips: '10 each direction' },
      { phase: 'Warm-Up', name: 'Bodyweight Squats', duration: 30, type: 'exercise', tips: '15 reps' },
      { phase: 'Warm-Up', name: 'Glute Bridges', duration: 25, type: 'exercise', tips: '15 reps' },
      { phase: 'Quads', name: 'Jump Squats', duration: 40, type: 'exercise', set: 1, reps: 12 },
      { phase: 'Quads', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Quads', name: 'Band Squats', duration: 45, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Quads', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Quads', name: 'Bulgarian Split Squats', duration: 50, type: 'exercise', set: 3, reps: '10 each' },
      { phase: 'Quads', name: 'Rest', duration: 45, type: 'rest' },
      { phase: 'Glutes', name: 'Glute Bridges', duration: 45, type: 'exercise', set: 1, reps: 15 },
      { phase: 'Glutes', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Glutes', name: 'Band Deadlifts', duration: 45, type: 'exercise', set: 2, reps: 15 },
      { phase: 'Glutes', name: 'Rest', duration: 30, type: 'rest' },
      { phase: 'Glutes', name: 'Clamshells', duration: 40, type: 'exercise', set: 3, reps: '15 each' },
      { phase: 'Glutes', name: 'Rest', duration: 40, type: 'rest' },
      { phase: 'Calves', name: 'Calf Raises', duration: 30, type: 'exercise', set: 1, reps: 20 },
      { phase: 'Calves', name: 'Rest', duration: 20, type: 'rest' },
      { phase: 'Calves', name: 'Seated Calf Raises', duration: 30, type: 'exercise', set: 2, reps: 20 },
      { phase: 'Cool-Down', name: 'Standing Quad Stretch', duration: 30, type: 'exercise', tips: '20s each' },
      { phase: 'Cool-Down', name: 'Pigeon Pose', duration: 30, type: 'exercise', tips: '20s each side' },
    ]
  },
  {
    id: 'core-15',
    title: 'Core Crusher',
    category: 'Core',
    duration: 15,
    intensity: 'medium',
    equipment: ['Bodyweight'],
    muscles: 'Abs · Obliques · Lower Back',
    desc: 'Targeted core workout with planks, crunches, and rotational exercises.',
    steps: [
      { phase: 'Warm-Up', name: 'Cat-Cow Stretch', duration: 30, type: 'exercise', tips: '30 seconds' },
      { phase: 'Warm-Up', name: 'Dead Bugs', duration: 30, type: 'exercise', tips: '10 each side' },
      { phase: 'Core Circuit', name: 'Plank Hold', duration: 45, type: 'exercise', tips: '45 seconds' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Bicycle Crunches', duration: 40, type: 'exercise', tips: '20 reps' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Mountain Climbers', duration: 40, type: 'exercise', tips: '20 each side' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Russian Twists', duration: 40, type: 'exercise', tips: '20 reps' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Leg Raises', duration: 40, type: 'exercise', tips: '15 reps' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Superman Hold', duration: 40, type: 'exercise', tips: '30 seconds' },
      { phase: 'Core Circuit', name: 'Rest', duration: 15, type: 'rest' },
      { phase: 'Core Circuit', name: 'Side Plank', duration: 30, type: 'exercise', tips: '15s each side' },
      { phase: 'Cool-Down', name: 'Child\'s Pose', duration: 30, type: 'exercise', tips: '30 seconds' },
    ]
  }
];

export const EQUIPMENT = [
  { id: 'bodyweight', name: 'Bodyweight', icon: '🧍', desc: 'No equipment needed' },
  { id: 'pull-up-bar', name: 'Pull-up Bar', icon: '单杠', desc: 'Doorway or wall-mounted' },
  { id: 'long-band', name: 'Long Band', icon: '➰', desc: 'Resistance band 41"+' },
  { id: 'short-bands', name: 'Short Bands', icon: '🔴', desc: 'Handle attachments' },
  { id: 'dumbbells', name: 'Dumbbells', icon: '🏋️', desc: 'Any weight' },
  { id: 'kettlebell', name: 'Kettlebell', icon: '🔔', desc: 'Single or pair' }
];

export const CATEGORIES = ['All', 'Full Body', 'Upper Body', 'Lower Body', 'Core'];

export function filterWorkouts(workouts, selectedEquipment, selectedCategory) {
  return workouts.filter(workout => {
    const matchesEquipment = selectedEquipment.length === 0 ||
      workout.equipment.some(eq => 
        selectedEquipment.some(se => 
          eq.toLowerCase().includes(se.toLowerCase()) ||
          se.toLowerCase().includes(eq.toLowerCase())
        )
      );
    const matchesCategory = selectedCategory === 'All' || workout.category === selectedCategory;
    return matchesEquipment && matchesCategory;
  });
}
